spring:
  config:
    activate:
      on-profile: prod-1
server:
  port: 9021

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
