spring:
  config:
    activate:
      on-profile: local-1

  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 9021

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
