spring:
  config:
    activate:
      on-profile: local-1

  data:
    redis:
      host: localhost
      port: 6379

  jwt:
    #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
    secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
    acccess-token-expire-time: 43200000 # 12시간
    refresh-token-expire-time: 604800000 # 7일
server:
  port: 9021

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
